#!/usr/bin/env node
// Regenerate the SDK's list of custom errors from the contracts that declare them.
//
// A custom error reaches a wallet as four bytes of selector and nothing else. Without a
// declaration to match it against, ethers reports "unknown custom error" — so every one of
// these carefully worded reverts arrives as a shrug, and the user is told only that
// something failed. The four reservation errors went missing from the hand-written list,
// which is how a registration that stopped at exactly the right guard looked like a mystery.
//
// Generated rather than maintained, because the failure mode of a hand-written list is
// silent: nothing breaks when a new error is added, it just stops being readable at the one
// moment someone needs to read it. errors.test.ts fails if this file drifts.
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

const ROOT = "contracts";
const OUT = "../sdk/src/errors.ts";

function walk(dir) {
  return readdirSync(dir).flatMap((e) => {
    const p = join(dir, e);
    return statSync(p).isDirectory() ? walk(p) : p.endsWith(".sol") ? [p] : [];
  });
}

// Generated verifiers declare none, and mocks declare errors that only exist to be triggered
// by tests — neither belongs in a list the app shows to users.
const files = walk(ROOT).filter((f) => !f.includes("/mocks/") && !f.includes("Verifier.sol"));

const found = new Map();
for (const f of files) {
  const src = readFileSync(f, "utf8");
  for (const m of src.matchAll(/error\s+([A-Za-z0-9_]+)\s*\(([^)]*)\)\s*;/g)) {
    const name = m[1];
    // Parameter names are dropped: a fragment needs types and order, nothing else.
    const params = m[2].trim() === ""
      ? []
      : m[2].split(",").map((a) => a.trim().split(/\s+/)[0]);
    const sig = `error ${name}(${params.join(",")})`;
    if (!found.has(sig)) found.set(sig, f);
  }
}

const sigs = [...found.keys()].sort();

const body = `// Generated by scripts/gen-errors.mjs — do not edit.
//
// Every custom error the contracts can revert with, as ABI fragments. A revert arrives as
// four bytes of selector; without these, ethers can only say "unknown custom error", and a
// message chosen to explain exactly what went wrong never reaches anyone.
//
// Regenerate with: npm run gen:errors  (from packages/protocol)
export const CONTRACT_ERRORS: readonly string[] = [
${sigs.map((s) => `  ${JSON.stringify(s)},`).join("\n")}
];
`;

writeFileSync(OUT, body);
console.log(`Wrote ${sigs.length} error fragments to ${OUT}`);
