import { expect } from "chai";
import { existsSync, readFileSync } from "fs";
import { join } from "path";

// The README's Sepolia table, checked against the deployment it claims to describe.
//
// It is generated by scripts/sync-readme.mjs, which the deploy runs — but a generator only
// helps if something notices when its output is stale, which is the same reason
// errors.test.ts exists beside gen-errors.mjs. Hand-editing the table, or committing a
// deployment without regenerating, fails here rather than in front of a reader who follows
// a dead Etherscan link.
describe("README Sepolia addresses", function () {
  const config = join(__dirname, "..", "..", "deployments", "networks", "sepolia.json");
  const readme = join(__dirname, "..", "..", "..", "README.md");

  it("match the deployment they describe", async function () {
    // Skipped rather than failed when there is no live deployment: tearing one down is a
    // legitimate state, and a suite that cannot pass without a testnet is a suite nobody runs.
    if (!existsSync(config)) return this.skip();

    const { renderTable } = await import("../scripts/sync-readme.mjs" as any);
    const cfg = JSON.parse(readFileSync(config, "utf8"));
    const md  = readFileSync(readme, "utf8");

    const from = md.indexOf("<!-- deployment:sepolia -->");
    const to   = md.indexOf("<!-- /deployment:sepolia -->");
    expect(from, "README lost its deployment markers").to.be.greaterThan(-1);
    expect(to).to.be.greaterThan(from);

    expect(
      md.slice(from + "<!-- deployment:sepolia -->".length, to).trim(),
      "README address table is stale — run `npm run readme:sync`",
    ).to.equal(renderTable(cfg));
  });
});
